### PR TITLE
add module for relational database modules

### PR DESCRIPTION
**Pull request by stbischof**

### CODE REVIEW

**Comment by stbischof** [comment]
@eclipse-daanse/eclipsefdn-releng please merge

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
automatic analysis with sonarcloud has been enabled.

As you prefer to use the automatic analysis, can we update the config to not provision a secret for the SONAR_TOKEN?
That also makes the addition of new repos a bit painful, as you need to create the repo first, then wait till sonarcloud picks it up, create a token for that repo and provision it.

**Comment by netomi** [comment]
ok so I checked in sonarcloud.io and the automatic analysis is not able to update itself. So we enabled it when the repo was still empty. At this point in time no languages have been detected ofc. Now you pushed java code, but the analysis page still showed no languages detected. I clicked the recheck button, and now he detected java. I will do the same for all other repos. That is really a downer.

**Comment by stbischof** [comment]
thx

so i need to inform you when this is merged?
https://github.com/eclipse-daanse/org.eclipse.daanse.rdb/pull/1

**Pull request merged**
