### PR TITLE
cleanup repocreation by using power of jsonnet

### PR DESCRIPTION
**Pull request by stbischof**
use newDaanseRepo

### CODE REVIEW

**Comment by stbischof** [comment]
@eclipse-daanse/eclipsefdn-releng

please review

**Comment by stbischof** [comment]
@netomi this needs your interaction since it addes the sonar secrets now to all projects

**Comment by netomi** [comment]
In general it looks good to me, except for the SONAR_TOKEN secret that is now added to all repo due to the template.
It references the token for the daanse-common repo. According to the documentation at sonarcloud (https://docs.sonarsource.com/sonarqube/latest/user-guide/user-account/generating-and-using-tokens/), the tokens could be project specific, so that each project (repo?) needs a separate token. That was the setup for other projects were each repo had its own token.

**Comment by stbischof** [comment]
but It would be still you job to create this projects. (sorry)

image

**Comment by netomi** [comment]
ok I will check with my colleague that setup the token and adapt the PR accordingly.

**Comment by stbischof** [comment]
could we merge this here until this does not harm the sonar creation issue?

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
ok the tokens have been provisioned for each repo and the project created in sonar cloud.

Unfortunately, there is no global analysis token for an organization, that seems to be available for SonarQube which is a different product.

**Comment by stbischof** [comment]
is it possible to set all sonar repos to automatic analyssis?

**Comment by netomi** [comment]
automatic analysis is enabled for all repos, however if that was your plan we would not have needed to create tokens and inject them for each repo which is a bit tedious and manual.

**Comment by stbischof** [comment]
since this would be way easier. automatic analysis seems to be the best way. and we get also pr support.

**Pull request merged**
