### PR TITLE
create common repo

### PR DESCRIPTION
**Pull request by stbischof**

### CODE REVIEW

**Comment by stbischof** [comment]
i am currently looking for more information about how/where to store secrets. that they are not published.

https://otterdog.readthedocs.io/en/latest/reference/organization/secret/#example-usage

what does this mean? wich path to what?
```
Pass: pass:<path/to/secret>
```

**Comment by netomi** [comment]
So we store credentials in an internal credential provider that we reference in the configuration. In order to share existing secrets / credentials with the EF, there is a page explaining options. After receiving the secret we will then correctly reference it in the configuration.

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Sharing-secrets

**Comment by netomi** [comment]
Is it intentional to remove the demo-repository repo?

**Comment by stbischof** [comment]
I thought thos was just a example for basic Template purpoaes. Since there did not exist a real repo with this name. (None that i can see) i removed it.

**Comment by netomi** [comment]
ah that is a private repo in the project, dont know how this came about, will ask my colleague about it.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live.

Permissions will be setup automatically by a different service within the next 2h, but you can already forks the repos.

**Pull request merged**
