### PR TITLE
add repos -  splitted from common

### PR DESCRIPTION
**Pull request by stbischof**

### CODE REVIEW

**Comment by stbischof** [comment]
@eclipse-daanse/eclipsefdn-releng

can you help me with that? i am not sure how i can handle this
```
!   settings {
!     default_code_security_configurations_disabled = false -> true
!   }
```

**Comment by netomi** [comment]
sorry, I am currently rolling out a new feature and not all projects are done applying the changes, will take a few more minutes and then it will be resolved.

**Comment by netomi** [comment]
you are ready to merge now, sorry for the inconvenience.

**Comment by stbischof** [comment]
@eclipse-daanse/eclipsefdn-releng @netomi 

how to handle the errors?

**Comment by netomi** [comment]
let me check

**Comment by netomi** [comment]
applied the missing changes with the cli tool:

```
Organization technology.daanse[id=eclipse-daanse]
  there have been 15 validation infos, enable verbose output with '-v' to to display them.

  
  ~ repository[name="org.eclipse.daanse.jakarta.servlet"] {
    ~ dependabot_security_updates_enabled = false -> true
    ~ secret_scanning                   = "disabled" -> "enabled"
    ~ secret_scanning_push_protection   = "disabled" -> "enabled"
    ~ web_commit_signoff_required       = false -> true
  ~ }

  + add repo_variable[name="SONAR_ORGANIZATION", repository="org.eclipse.daanse.jakarta.servlet"] {
    + name                              = "SONAR_ORGANIZATION"
    + value                             = "eclipse-daanse"
  + }

  + add repo_variable[name="SONAR_PROJECT_KEY", repository="org.eclipse.daanse.jakarta.servlet"] {
    + name                              = "SONAR_PROJECT_KEY"
    + value                             = "eclipse-daanse_org.eclipse.daanse.jakarta.servlet"
  + }

  + add branch_protection_rule[pattern="main", repository="org.eclipse.daanse.jakarta.servlet"] {
    + allows_deletions                  = false
    + allows_force_pushes               = false
    + blocks_creations                  = false
    + bypass_force_push_allowances      = []
    + bypass_pull_request_allowances    = []
    + dismisses_stale_reviews           = false
    + is_admin_enforced                 = false
    + lock_allows_fetch_and_merge       = false
    + lock_branch                       = false
    + pattern                           = "main"
    + require_last_push_approval        = false
    + required_approving_review_count   = "0"
    + required_status_checks            = [
      + "eclipse-eca-validation:eclipsefdn/eca"
    + ],
    + requires_code_owner_reviews       = false
    + requires_commit_signatures        = false
    + requires_conversation_resolution  = false
    + requires_deployments              = false
    + requires_linear_history           = true
    + requires_pull_request             = true
    + requires_status_checks            = true
    + requires_strict_status_checks     = true
    + restricts_pushes                  = false
    + restricts_review_dismissals       = false
  + }

  
  ~ repository[name="org.eclipse.daanse.jdbc.datasource.metatype.h2"] {
    ~ dependabot_security_updates_enabled = false -> true
    ~ secret_scanning                   = "disabled" -> "enabled"
    ~ secret_scanning_push_protection   = "disabled" -> "enabled"
    ~ web_commit_signoff_required       = false -> true
  ~ }

  Do you want to perform these actions? (Only 'yes' or 'y' will be accepted to approve)

  Enter a value: y

  Applying changes:

  [####################################]  100%          
  Done.
  
  Executed plan: 3 added, 8 changed, 0 live resources ignored.

```

first time I see a problem like that, maybe the creation of a repo took a bit longer as usual and thus subsequent changes that relied on that repo failed. Will add there some additional check to wait till the repo has been created to prevent that from happening.

**Comment by stbischof** [comment]
I still do not have merge rights on the repos.
My user is not assigned

**Pull request merged**
