### PR TITLE
rm org.eclipse.daanse.common - content now exists in separate repos

### PR DESCRIPTION
**Pull request by stbischof**

### CODE REVIEW

**Comment by stbischof** [comment]
yes, this should be removed.


I have an other that should be renamed. how to handle this?

**Comment by netomi** [comment]
to rename a repo you can follow the guide here:

https://otterdog.readthedocs.io/en/latest/userguide/renaming/#supported-resources

**Comment by stbischof** [comment]
@netomi  you are so duper fast. every time!! thx a lot !

**Comment by stbischof** [comment]
so i will do an other pr with the renaming.

**Review by netomi — APPROVED** [review]

**Pull request merged**
